### PR TITLE
 ENH (issue #49): Added DiffusionConvolution, tests and a script to easily build docs locally.

### PR DESCRIPTION
**Pull request by LeviBorodenko**
- Added `DiffusionConvolution` to `layers.convolutional`. Also covered it in tests and made sure the docs look good.
- Improved docs for `SortPool` and covered it in globalpool tests (removed from pool tests).
- Added both `SortPool` and `DiffusionConvolution` to `autogen.py` so it is contained in the docs.
- added `docs/local_build.sh` which is a script that installs the current spektral build from the local branch, builds docs and serves them on a local web server.
 For convenience.

### CODE REVIEW

**Comment by danielegrattarola** [comment]
Thank you very much for adding this! 
I think it's good to merge unless you want to make other changes.

**Comment by LeviBorodenko** [comment]
No problem :)

This should be good to merge!

**Comment by danielegrattarola** [comment]
Great! Thanks again!!

**Comment by danielegrattarola** [comment]
This was merged into `master` and I also released v0.5.0 of the library on PyPi. 

Cheers, 
Daniele

**Pull request merged**
