### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by lucasmiranda42**
Hi!

I updated setup.py for the package to reflect specific dependencies when running on Apple Silicon (it now installs tensorflow-macos instead of tensorflow when this is the case). It solved some problems I was having when integrating spektral into a package whose dependencies I'm managing using poetry. It may help others too :)

I tested it on an M1 MacBook Pro, installing both via pip and poetry. I'm open for suggestions regarding other implementations of the same fix, if you're interested.

Best!
Lucas

### CODE REVIEW

**Comment by lucasmiranda42** [comment]
Hi, all! Sorry to bother yet again!

Is there any chance you can look into this? I think it would really simplify installation in Apple Silicon devices :)

Best, and happy holidays! :)
Lucas

**Comment by danielegrattarola** [comment]
Sorry for the late reply but my notifications were messed up and I wasn't receiving emails. 

This change assumes that all ARM platforms are Apple Silicon, is there a way to make it more specific? 
Also, is `tensorflow-macos` the only TF version for apple silicon or is it still possible to install vanilla TF?

**Comment by DavideWalder** [comment]
> Sorry for the late reply but my notifications were messed up and I wasn't receiving emails.
> 
> This change assumes that all ARM platforms are Apple Silicon, is there a way to make it more specific? Also, is `tensorflow-macos` the only TF version for apple silicon or is it still possible to install vanilla TF?

This can be specified as done here: https://github.com/keras-team/keras-nlp/blob/d9330fa054bac3d2e53f660b8c723c92da4ebac0/setup.py#L45
Source: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

I assume that `tensorflow-macos` can only be installed on MacOS using arm (to be checked). In that case the dependency specification could look like:
```cfg
install_requires =
    tensorflow>=2.2.0;platform_machine != "arm64" or platform_system != "Darwin"
    tensorflow-macos>=2.5.0;platform_machine == "arm64" and platform_system == "Darwin"
```
Worth pointing out that all of this can be done declaratively using `setup.cfg` or `pyproject.toml`, without having to write custom code.

**Comment by danielegrattarola** [comment]
Ok, I think it's time to update the build config for Spektral. 
I'll use this PR to implement the changes before merging

**Comment by danielegrattarola** [comment]
Thanks @lucasmiranda42 for brining this to my attention and thanks @DavideWalder for the suggestion. 

Cheers

**Pull request merged**
