### PR TITLE
 [ENH: issue #58] Realtime conversion from disjoint to batch.

### PR DESCRIPTION
**Pull request by LeviBorodenko**
Added ops to turn disjoint signals and adjacencies into batches.

- `ops.disjoint_signal_to_batch` is a function that turns disjoint graph signals into batch mode graph signals with the usual padding
- `ops.disjoint_adjacency_to_batch` turns disjoint adjacencies into batch mode graph signals. Also with the usual padding.
- Added tests for both.
- Started work on the `Disjoint2Batch` layer

### CODE REVIEW

**Comment by LeviBorodenko** [comment]
I don't think anything I added should cause the check to fail. Looks like there is something wrong with the example.

**Comment by danielegrattarola** [comment]
Yes, I pushed a fix for this issue to `master` a while back but I forgot to merge it into `develop`, don't worry about it. 
The code looks good so far, let me know when you think it's good to go

**Comment by LeviBorodenko** [comment]
Alright, the `Disjoint2Batch` layer is finished, tested and documented. `SortPool` now also accepts disjoint signals.

Ready for merging.

**Comment by danielegrattarola** [comment]
Thanks Levi!! Just merged it into the dev branch.

Cheers, 
Daniele

**Pull request merged**
