### PR TITLE
Adding XENet 

### PR DESCRIPTION
**Pull request by JackMaguire**
Hi Daniele. Maybe this is a little premature for a PR, but I copy/pasted the sparse XENet draft here with a link to the preprint. I'd love to add support for dense inputs but maybe I'll wait until next week to get started on that

### CODE REVIEW

**Comment by JackMaguire** [comment]
> I'd love to add support for dense inputs

Looks like that is tough with the `MessagePassing` base class. Would you say it is appropriate to have `XENetSparseConv` and `XENetDenseConv`? And maybe `XENetConv` can just divert to whichever one is appropriate?

**Comment by JackMaguire** [comment]
I'll add more to the tests next week to get better code coverage.

**Comment by danielegrattarola** [comment]
Hi Jack, 

yes, I think it's better to keep the behavior for dense/sparse separate and use the proper `call()` according to the input. 
The behavior should be similar to e.g. GATConv:

https://github.com/danielegrattarola/spektral/blob/e99d5955a80eeae3c4605d8479f53aaa0ef5dbf2/spektral/layers/convolutional/gat_conv.py#L164-L170

I'll have a look at the PR asap and make the appropriate changes!

Cheers
Daniele

**Comment by JackMaguire** [comment]
Sounds good, thanks Daniele! You can see where I got stuck - the two implementations have different base classes so I was a deer in headlights

**Comment by danielegrattarola** [comment]
Turns out it would have been much more messy to integrate everything in one layer, so let's stick with the separate classes (I might even update other layers to have the same structure, we'll see...)
Anyway, this is good to go if you want to merge. 

Cheers

**Comment by JackMaguire** [comment]
> Turns out it would have been much more messy to integrate everything in one layer

Yeah, honestly I was looking forward to seeing how you planned to pull it off because it looked very challenging to me.

I'm happy with this but you get final say. Merge when ready

**Pull request merged**
