### PR TITLE
XENetDenseConv with N=None

### PR DESCRIPTION
**Pull request by JackMaguire**
@SajidAhmeduiu caught this issue with XENet when running with an arbitrary number of nodes. It looks like this was just a misuse of `x.shape[1]` instead of `tf.shape(x)[1]`. These changes appear to fix the problem but I have not yet tried this new implementation in a production run.

### CODE REVIEW

**Comment by JackMaguire** [comment]
I'm also not quite sure what those first 3 commits are from. Perhaps this is the first PR since the latest merge from develop -> master?

**Comment by danielegrattarola** [comment]
Hi, 

thanks for making this, it looks good to go except for that failure with Black. 

I'm actually OOO  without a laptop right now, so I have no way of fixing it this week. I'll do it as soon as possible and merge it into `develop`

Cheers

**Comment by danielegrattarola** [comment]
Thanks,Jack, this is now merged into `develop` and `master` and I have published v1.0.8 on PyPi, which includes this fix.

**Comment by JackMaguire** [comment]
Thanks Daniele! Sorry for not running the whitespace checks myself. I'll try and do that next time

**Comment by danielegrattarola** [comment]
No worries at all, it's just ordinary repo maintenance.
Cheers

**Pull request merged**
